### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chromer030** [macchrome/linchrome#1]
Hi , Thank you for your perfect releases.
Is it possible to include Hardware Acceleration Video Decode patch for Linux release and also Sync feature?

**Comment by macchrome** [comment]
Hardware Acceleration Video Decode yes. Sync no way: ungoogled!

https://github.com/macchrome/linchrome/releases/download/v79.0.3945.130-r706915-portable-ungoogled-Lin64/ungoogled-chromium_79.0.3945.130-7.vaapi-2_linux.tar.xz

View the release page for vital install requirements, supply your own Widevine.

**Comment by chromer030** [comment]
Thank you very very much
