### ISSUE TITLE
Args.gn request

### ISSUE THREAD

**Issue by Alex313031** [macchrome/linchrome#14]
Hello, I'm coming here and asking the same thing I asked Rob Rich. I didn't have to for Hibbiki, but unfortunately he stopped a while ago, and then even deleted all the builds except his last M75.x.x version. I used his 49 build for xp machines and older ones for older machines. Sigh, at least web.archive.org kept most of em. Anyway, since yall's args.gn arent posted like Hibbiki's was, I'm asking for them (only the linux ones). I use your's and rob's builds on windows but not on linux. Im asking because I would like to use yours and his as a base, and kind of do a three way merge between yalls, i.e. your build flags, with his profiling flags, as well as adding my own widevine, API keys for sync, and some overlay tweaks as well as using hibbikis HEVC patch, ported for linux (to enable native H.265.) Might I suggest, (at your own discretion) posting your args.gn along with the readme, so that other people can use them. Even if they aren't modifying anything, one might want to make an older build, or newer one, using the same build config as you. Also thanks for adding to the work of eloston. Would you ever consider making a vanilla build for linux, i.e. not ungoogled.

**Comment by macchrome** [comment]
################################
## Ungoogled Portable Linux GN arguments
################################
build_with_tflite_lib=false
clang_use_default_sample_profile = false
clang_use_chrome_plugins=false
#closure_compile=false
enable_hangout_services_extension=false
enable_mdns=false
enable_mse_mpeg2ts_stream_parser=true
enable_nacl=false
enable_nacl_nonsfi=false
enable_one_click_signin=false
enable_reading_list=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_widevine=true
exclude_unwind_tables=true
fieldtrial_testing_like_official_build=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
optimize_webui=false
safe_browsing_mode=0
treat_warnings_as_errors=false
use_official_google_api_keys=false
use_unofficial_version_number=false
blink_symbol_level=0
###custom_toolchain="//build/toolchain/linux/unbundle:default"
enable_iterator_debugging=false
enable_swiftshader=true
fatal_linker_warnings=false
ffmpeg_branding="Chrome"
###host_toolchain="//build/toolchain/linux/unbundle:default"
is_clang=true
is_debug=false
is_official_build=true
###linux_use_bundled_binutils=false
proprietary_codecs=true
symbol_level=0
use_gnome_keyring=false
#########################use_jumbo_build=true
use_kerberos=false
use_sysroot = true 
enable_platform_hevc = true
enable_platform_ac3_eac3_audio = true
enable_platform_mpeg_h_audio=true 
enable_platform_dolby_vision=true 
is_component_ffmpeg = false
use_vaapi=true 
#####clang_base_path = "/home/acer/stage-final-87"
clang_base_path = "/mnt/f0fc0d51-fce6-460b-bc47-c702b4abe99f/stable/chromium/src/third_party/llvm-build/Release+Asserts" 
#######  PGO PGO
chrome_pgo_phase = 2
#pgo_data_path="/home/acer/chromium/src/chrome-linux-4389-1615484746-845f8166c73d01aac66fc676e3122d92508416a9.profdata"
pgo_data_path="/volumes/disk1/chromium-92.0.4515.131/chrome-linux-4515-1627572323-7b80f2d12f40afe6f7872c5528a069e31662276b.profdata"
#######
use_thin_lto = true
thin_lto_enable_optimizations = true
use_lld = true
##sysroot="/volumes/disk1/chromium-90.0.4430.85/build/linux/debian_sid_amd64-sysroot"
sysroot="/volumes/disk2/stable/chromium/src/build/linux/debian_sid_amd64-sysroot"
################### use_system_libdrm=false        ChromeOS
################### use_system_minigbm=false    ChromeOS
enable_js_type_check=false
###############################################
### <<  END >> #######################################


All major GNU/Linux distributions have a vanilla build of Chromium/Chrome.

**Comment by Alex313031** [comment]
Thanks m8. And yeah I know but sometimes they're out of date, only debian has sync by default, and often they don't have widevine. Currently using (some) of your flags on M93 rn! (M94 has major bugs bc its so new) Unfortunately the HEVC patch has been broken since M90, have you looked into enabling H.265 at all? (EDIT: I see there is the gn flags for it, but unfortunately thats not enough on anything besides windows.)
As a side note, I am also building ChromiumOS, using [https://arnoldthebat.co.uk/wordpress/](url) (Arnold the Bat's) overlays as a starting point. I have a build that works well, with full linux firmware and modules, but lacking H264. If you are interested or maybe you have already tried out Chromium OS or Cloudready, I'd be happy to share the disk image (can be used straight from USB, without touching system)

**Comment by Alex313031** [comment]
Sorry, another question. I have the annoying "sometimes the keyring unlocks sometimes not" that plagues pretty much anything but a stock gnome or ubuntu install (Im using Openbox), does the 'use_gnome_keyring=false' effectively have the same effect as if one were to pass '--password-store=basic' on the command line, or does it make chromium search for a keyring manager like normal, just ignoring gnome's keyring?

**Comment by macchrome** [comment]
1. Ungoogled Chromium for Linux would not compile cleanly  without 'use_gnome_keyring=false'. 

2. In the Chromium master branch (circa June 2021 onwards), HEVC may be enabled (by default) if the build flag ENABLE_PLATFORM_ENCRYPTED_HEVC is set in args.gn AND  if the cmdline has --enable-clear-hevc-for-testing

**Comment by Alex313031** [comment]
How did you find out about the hevc cmdline flag.
