### ISSUE TITLE
Install chromium and ungoogled chromium at the same time without conflicts

### ISSUE THREAD

**Issue by trimechee** [macchrome/linchrome#17]
Hello, Linchrome is wonderful and amazing, thank you very much !
Please I have a problem: I installed Chromium 94 with sync from woolyss website (made by Hibbiki) then I installed Ungooled Chromium 94 of Mr Macchrome because I want to have these two distinct browsers for different uses but after the installation of ungooled chromium compiled by Macchrome, Unggoled chromium made by Macchrome replaced my chromium with sync  and took the place of my chromium browser, please can you fix this problem by changing the name of chrome processes to unggoled chromium or change the default folder location of ungoogled chromium so that I can use these two browsers at the same time ?
Thank you so much !

**Comment by macchrome** [comment]
http://peter.sh/experiments/chromium-command-line-switches/

--user-data-dir

**Comment by trimechee** [comment]
Wonderful ! Thank you very much for your precious help :)
