### ISSUE TITLE
 Exist similar version of Chromium that possible to install?

### ISSUE THREAD

**Issue by vampywiz17** [macchrome/linchrome#2]
Hello there,

It is the only one version (Thanks for that!!!) that able to decode h265 videos (I use it to watch sec. cams)

It possible to install a similar Chromium (all codec) to Fedora 32? (single RPM, or Repo).

**Comment by macchrome** [comment]
In theory, this version of Chromium should be portable and run on all x86_64 variants of GNU/Linux. 

External build requirements are listed (for Ubuntu): https://github.com/macchrome/linchrome/releases/tag/v83.0.4103.97-r756066-portable-ungoogled-Lin64

Unarchive, execute and install any dependencies that are required. I'm not willing specifically to maintain a version for Fedora; but, time permitting, will check-out the execution of this version of Chromium under Fedora 32.

**Comment by vampywiz17** [comment]
@macchrome Your version is work well on Fedora. My real question is, that exist any installable (eg. rpm package + regularly updated repo ) Chromium that contain all codecs? (like your edition)

i try chromium-freeworld (with chromium-freeworld-libs-media addon) and chromium-vaapi (same, older version) from rpm-fusion, but not work at all... 

This packages (chromium-freeworld+libs-media addon) say "support all possible codecs" but the h265 cam pictures only working on your version.  

Your version is good, but now i need to use two browser:

Your version: See h265 camera pictures

Regular Chrome/Chromium: Everything else :)

The reason that i use "regular" chrome next to your version, that is update automatically, contain google stuffs and so on...

**Comment by vampywiz17** [comment]
I ask chromium-freeworld github page, that possible to do the same with you. You able to help as, how to solve this problem?

https://github.com/UnitedRPMs/chromium-freeworld/issues/10
