### ISSUE TITLE
HEVC question.

### ISSUE THREAD

**Issue by Alex313031** [macchrome/linchrome#20]
I noticed these have HEVC/H.265 support. How are you achieving this? Are you using patches or certain args.gn arguments?

Because my chromium fork, thorium, still doesn't play HEVC content. These are the args.gn for the linux releases > https://github.com/Alex313031/Thorium/blob/main/args.gn

**Comment by macchrome** [comment]
v104 onwards, HEVC hardware accelerated support is standard, HEVC software support is optional:

https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding

**Comment by Alex313031** [comment]
@macchrome Oh ok. I thought they only enabled it for Windows. It's available for all platforms, but the reason it isn't working for me is I'm not using the SW decoding patch, and I'm on linux + nvidia (GTX 970), which doesn't support HEVC HW decoding on linux, even with the proprietary drivers.

Is that SW decoding patch rebased on tip o tree chromium, or stable? Like could I just follow his instructions and use it as a drop in patch for thorium. Because otherwise, Im sorry but im not about to manually rebase that many files every release by cross referencing and adding/removing those lines on tip o tree source files lolol.

Also, do you know if they will ever bring SW decoding for non-encrypted hevc upstream?

**Comment by macchrome** [comment]
1. Threre are versions of StaZhu's SW decoding patch for 103-106: choose the relevant version.

2. From v104 there is no distinction between a non-encrypted and encrypted SW decoded HEVC stream. I doubt if SW decoding hevc will ever be brought upstream.
