### ISSUE TITLE
Driver for version 105.0.5177 does not exist (Chromium Driver)

### ISSUE THREAD

**Issue by hjames034** [macchrome/linchrome#22]
When using webdriver-manager module in Python, I have recently run into the following error:

ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_105.0.5177

As a result, the Chromium web driver cannot be opened, and my program cannot run. Has the driver for v105.0.5177 stopped working?

**Comment by macchrome** [comment]
The latest (version appropriate) chromedriver is included with the Chromium v105.0.**5195**.x package.

Seriously, what do you want me to do!
