### ISSUE TITLE
can you please share build instruction or build regualr chromium not Ungoogled?

### ISSUE THREAD

**Issue by oksakhartman** [macchrome/linchrome#28]
can you please share build instruction or build regualr chromium not Ungoogled?

thanks

**Comment by macchrome** [comment]
https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md	

https://github.com/ungoogled-software/ungoogled-chromium

vaapi: https://github.com/ungoogled-software/ungoogled-chromium-archlinux
