### ISSUE TITLE
amazing work. how to reproduce?

### ISSUE THREAD

**Issue by devopsss** [macchrome/linchrome#29]
![image](https://github.com/macchrome/linchrome/assets/33988562/a68a44f1-d314-48f9-8512-123f79ae199b)

how to reproduce this menu option on regular ungoogled-chromium?
thanks for your hard work!

**Comment by macchrome** [comment]
https://github.com/uazo/cromite/tree/master/build/patches

1. Disable-third-party-origin-trials.patch
2. 00Disable-FirstPartySets-and-StorageAccessAPI.patch
3. bromite-build-utils.patch
4. Content-settings-infrastructure.patch
5. JIT-site-settings.patch
6. Add-webGL-site-setting.patch
7. Add-webRTC-site-settings.patch
8. Enable-third-party-storage-partitioning.patch
9. fix-site-settings.patch
