### ISSUE TITLE
Chrome Web Store

### ISSUE THREAD

**Issue by chromer030** [macchrome/linchrome#3]
Hi , thank you for releases , hardware decoding on this release working great.
but we cant install extensions and themes from Chrome Store !

![Screenshot_2020-06-18_11-29-47](https://user-images.githubusercontent.com/13361552/85059453-31adbd00-b193-11ea-8133-470f73324699.png)

**Comment by macchrome** [comment]
Is the inability to install extensions and themes from the Chrome Store particular to the present build?

Extensions can be installed by deploying "developer mode" and sideloading an unpacked extension. For example, to obtain the developer version of umatrix:

https://chrome.google.com/webstore/detail/umatrix-development-build/eckgcipdkhcfghnmincccnhpdmnbefki

curl -L "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=83.0&x=id%3Deckgcipdkhcfghnmincccnhpdmnbefki%26installsource%3Dondemand%26uc"  >  umatrix.crx

I'm not particular concerned whether extensions and themes can be installed directly from the Chrome Store: the software is called ungoogled chromium portablelinux and it's up to the user to familarise his or herself with the limitations of the format.

**Comment by chromer030** [comment]
Yes , it's on Chromium v83.0.4103.106-r756066.
but Thank you for explanation , via developer mode it's possible to install and use every extension.
Thanks again.
