### ISSUE TITLE
Add patch that fixes memory leak on X11 from Arch version of Ungoogled Chromium

### ISSUE THREAD

**Issue by cypherpunk1984** [macchrome/linchrome#30]
A ton of people, myself included, are reporting a memory leak when using VAAPI with latest versions of Ungoogled Chromium, and X11 server crashing when closing the browser producing a complete system freeze. Arch Linux version devs found a fix that maybe could be useful on debian/ubuntu/etc versions:

Patch here:
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/8cac7af0ab8e3c0ceea6fc2f2bb187744a7cae0c

Info here:
https://bbs.archlinux.org/viewtopic.php?pid=2123383#p2123383

**Comment by macchrome** [comment]
Ok

**Comment by cypherpunk1984** [comment]
Update: Since version 119 from official ungoogled-software repo, the memory leak doesn't exist any longer, seems that Google fixed it.
Everything seems to be working perfectly (drivers, hardware acceleration, etc.) since 119 on Intel hardware.
