### ISSUE TITLE
Update release description with proper flags

### ISSUE THREAD

**Issue by cypherpunk1984** [macchrome/linchrome#31]
"To enable vaapi:

--disable-features=UseChromeOSDirectVideoDecoder for vaapi
--enable-features=VaapiVideoDecoder in cli. (or enable-accelerated-video-decode)
Disable HEVC vaapi playback requires CLI flag: --disable-features=PlatformHEVCDecoderSupport"

The first one isn't needed anylonger with newer versions, hardware acceleration works anyway without it. In fact in my system I need to remove it, otherwise hardware acceleration doesn't work.
The second one, when using Linux, needs to be switched to the new one: --enable-features=VaapiVideoDecodeLinuxGL
The third one isn't needed for hardware acceleration, you should mention it is just an option in case the system doesn't support HEVC. I don't use that flag and vaapi/hardware acceleration is enabled.

**Comment by macchrome** [comment]
I'll finalise the flags when vaapi for AMD GPUs is fixed.

**Comment by cypherpunk1984** [comment]
> I'll finalise the flags when vaapi for AMD GPUs is fixed.

Someone created a patch for Mesa that makes VAAPI on AMD hardware to work. So it seems it was a Mesa issue with VAAPI, not a Chromium issue. Give it a try if you are on AMD.

https://bbs.archlinux.org/viewtopic.php?pid=2125225#p2125225

**Comment by macchrome** [comment]
I'm not interested in third party _ad hoc_ fixes.

Google seems to have  realised the folly of its way: https://chromium-review.googlesource.com/c/chromium/src/+/4938496
