### ISSUE TITLE
Build v123.0.6312.90-r1262506 - Raw Draw bug

### ISSUE THREAD

**Issue by cypherpunk1984** [macchrome/linchrome#32]
On this build, if you add the flag

`--enable-features=RawDraw`

the browser opens but the rendering is all bugged. At least that is what happens on an Intel system.

Previous build was working perfectly with that flag.

Temporary solution: remove the flag, you lose raw draw but everything else works normally.

**Comment by macchrome** [comment]
chrome://flags/#enable-raw-draw

Enable raw draw
!!! NOTE: THIS FLAG IS EXPIRED AND MAY STOP FUNCTIONING OR BE REMOVED SOON !!! When enabled, web content will be rastered on output surface directly. – Mac, Windows, Linux, ChromeOS, Android, Fuchsia, Lacros

[#enable-raw-draw](chrome://flags/#enable-raw-draw)
