### ISSUE TITLE
GLIBC

### ISSUE THREAD

**Issue by szanalmas** [macchrome/linchrome#34]
Hi!

"Chromium 129.0.6668.96 (Official Build) (64-bit)
Built on Ubuntu 22.04.4 LTS (GNU/Linux 6.10.2 x86_64)"

"Chromium 128.0.6613.114 (Official Build) (64-bit)
Built on Ubuntu 22.04.4 LTS (GNU/Linux 6.10.2 x86_64)"

What changed?
129.0.6668.96 version won't start, libffmpeg.so requires GLIBC 33 minimum?

GLIBC 31 was enough for Chromium 128.0.6613.114, this worked well for me. (debian 11.2)

Thnx.

**Comment by macchrome** [comment]
I packed my personal  Ubuntu Noble assembled xhe-aac  enhanced libffmpeg.so by mistake!

Either substitutte libffmpeg.so with the one from V128 or download https://github.com/macchrome/linchrome/releases/download/v129.6668.97-M129.0.6668.97-r1343869-portable-ungoogled-Lin64/ungoogled-chromium_129.0.6668.97_2.vaapi_linux.tar.xz

Hopefully, that should solve the problem: when cross-compiling under Jammy a sys_root is now required; but that should not impact the Linux build which I always compiled with a sysroot.

**Comment by szanalmas** [comment]
Thank you your response!

Yesterday I tried to restore the previous ffmpeg.so, but it did not render the fonts.
I disabled RawDraw today and it's fine.
Do I need RawDraw? (I have used so far)

**Comment by macchrome** [comment]
chrome://flags/#enable-raw-draw

Enable raw draw
!!! NOTE: THIS FLAG IS EXPIRED AND MAY STOP FUNCTIONING OR BE REMOVED SOON !!! When enabled, web content will be rastered on output surface directly. – Mac, Windows, Linux, ChromeOS, Android, Lacros

[#enable-raw-draw](chrome://flags/#enable-raw-draw)

The RawDraw flag is obsolete, it should be disabled: --disable-features=RawDraw

**Comment by szanalmas** [comment]
Thank you!
