### ISSUE TITLE
Thanks and Suggestion

### ISSUE THREAD

**Issue by lfom** [macchrome/linchrome#6]
Hello, thank you for this up-to-date version of Ungoogled Chromium for Linux. I have installed it on Pop!_OS 20.10 (like Ubuntu 20.10) and it worked flawlessly. It already had libva.so.2.800.0 so I didn't have to do anything else.

Just curious: is there any reason you do not want your builds listed in the Ungoogled Chromium page? If you need more info about how to make a request:
https://github.com/ungoogled-software/ungoogled-chromium-binaries

Regards

**Comment by macchrome** [comment]
You know where to find my releases.
