### ISSUE TITLE
I would love to see it on AUR.

### ISSUE THREAD

**Issue by lucaslira95** [macchrome/linchrome#7]
This build is so complete and functional, i would love to see these binaries released on AUR.
AUR already have eloston version, but not all codecs and no widevine, and we have to wait it compile, so it would be great to simple run a command and install it quick, all complete and smooth.

**Comment by macchrome** [comment]
You know where to find my releases.

**Comment by lucaslira95** [comment]
yes, I know where to find the actual releases, but would be good to have these binaries in AUR

**Comment by zocker-160** [comment]
@lucaslira95 it is impossible to put it in AUR, since unofficial binaries are not allowed. An `ungoogled-chromium-bin` has existed multiple times, but it got removed by moderators every time, because of "untrusted source".

**Comment by lucaslira95** [comment]
@zocker-160 well, it could be on Unnoficial User Repository, but anyway, i'm using the one from chaotic-aur

**Comment by zocker-160** [comment]
> @zocker-160 well, it could be on Unnoficial User Repository, but anyway, i'm using the one from chaotic-aur

@lucaslira95 `chaotic-aur` is an unofficial user repository, isn't it? Or do you refer to something else?
