### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by illeng** [macchrome/linchrome#8]
Please i cant seem to install it on my Zorin OS. Can you help me with this.

Thanks

**Comment by macchrome** [comment]
The necessary installation instructions are at:

https://github.com/macchrome/linchrome/releases/tag/v90.0.4430.85-r857950-portable-ungoogled-Lin64

"ldd chrome"  to find any missing dependencies.

**Comment by illeng** [comment]
I'm sorry to bother you again, but I still don't know how to install it. 
I am still new to Linux, and i need a privacy browser. I started researching the ungoogled chromium and stumbled on https://chromium.woolyss.com. After following the site closely, i noticed that they updated the versions on there faster and regularly. I would appreciate if you can give me steps and commands to install this browser on my computer. Better still, is there any way I can get an AppImage for your version? I would appreciate hearing from you.

**Comment by macchrome** [comment]
ungoogled-chromium_90.0.4430.93_1.vaapi_linux.AppImage
https://github.com/macchrome/linchrome/releases/download/v90.0.4430.93-r857950-portable-ungoogled-Lin64/ungoogled-chromium_90.0.4430.93_1.vaapi_linux.AppImage
SHA1 E5BD1E3B2CFC94EA8BF60EF66DCA1DC07ED27B33

https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/90.0.4430.85-1.1

Read the "README" for additional instructions.

**Comment by illeng** [comment]
Hi
First of all, I need to say a big thank you for taking out time to create/provide an AppImage for your ungoogled chromium browser version. I honestly didn't expect it, but i am delighted you did. I revisited your website on the browser, and i noticed it states that my version is "up-to-date" and comes with "all-codecs+" only. Unlike how it is listed with Marmaduke's Archive, which is "up-to-date" "ungoogled" and comes with "widevine" "all-codecs+" 
Do you think this is accurate?
I have attached a screenshot for you.
On Tue, May 4, 2021 at 12:07 PM, macchrome ***@***.***> wrote:
 ungoogled-chromium_90.0.4430.93_1.vaapi_linux.AppImage
 https://github.com/macchrome/linchrome/releases/download/v90.0.4430.93-r857950-portable-ungoogled-Lin64/ungoogled-chromium_90.0.4430.93_1.vaapi_linux.AppImage (https://github.com/macchrome/linchrome/releases/download/v90.0.4430.93-r857950-portable-ungoogled-Lin64/ungoogled-chromium_90.0.4430.93_1.vaapi_linux.AppImage)
 SHA1 E5BD1E3B2CFC94EA8BF60EF66DCA1DC07ED27B33
 https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/90.0.4430.85-1.1 (https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/90.0.4430.85-1.1)
 Read the "README" for additional instructions.

**Comment by macchrome** [comment]
Check for yourself:

https://tools.woolyss.com/html5-audio-video-tester/
